# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Build.ps1
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: '; PrivateBuild'

- task: PublishTestResults@2
  displayName: 'Publish Test Results ./build/test/*.trx'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'build/test/*.trx'
    mergeTestResults: true
    testRunTitle: 'CI Tests'
  continueOnError: true
  condition: succeededOrFailed()
